import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createInterface } from 'node:readline/promises';
import { stdin as defaultInput, stdout as defaultOutput } from 'node:process';
import { validateStrictWorkspace } from './strict-check.js';
import { validateCoreFile } from './validators.js';
import { inspectWorkspace } from './inspect.js';

export const interviewSchema = JSON.parse(
  fs.readFileSync(new URL('./interview-schema.json', import.meta.url), 'utf8')
);

const coreFiles = [
  'product/product-brief.zh-CN.md',
  'product/scope-gate.zh-CN.md',
  'product/screen-states.zh-CN.md',
  'product/data-safety.zh-CN.md'
];

const generatedMarker = '<!-- Generated by Jumao from focused intake. Edit this file freely. -->';
const rootDir = path.resolve(fileURLToPath(new URL('../..', import.meta.url)));

export async function collectInterviewAnswers(input = defaultInput, output = defaultOutput) {
  const rl = createInterface({ input, output });
  try {
    const answers = {};
    for (const question of orderedInterviewQuestions(interviewSchema)) {
      const value = await rl.question(`${question.title} `);
      setAnswerAtPath(
        answers,
        question.answerPath,
        question.inputType === 'list' ? splitList(value) : value
      );
    }
    return answers;
  } finally {
    rl.close();
  }
}

export function orderedInterviewQuestions(schema) {
  const stageOrder = new Map(schema.stages?.map((stage) => [stage.id, stage.order]) ?? []);
  const fallbackStageID = schema.stages?.[0]?.id;
  return [...schema.questions].sort((left, right) => {
    const leftStageOrder = stageOrder.get(left.stage ?? fallbackStageID) ?? Number.MAX_SAFE_INTEGER;
    const rightStageOrder = stageOrder.get(right.stage ?? fallbackStageID) ?? Number.MAX_SAFE_INTEGER;
    return leftStageOrder - rightStageOrder || left.order - right.order;
  });
}

export function readAnswersFile(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

export function runInterview(targetDir, answers, options = {}) {
  const focusedIntake = focusedIntakeFrom(answers);
  if (focusedIntake) {
    const outputPath = path.join(targetDir, '.jumao', 'intake-answers.json');
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, `${JSON.stringify({
      schemaVersion: 1,
      mode: focusedIntake.mode,
      answers: focusedIntake.answers,
      updatedAt: new Date().toISOString()
    }, null, 2)}\n`, 'utf8');
    return writeFocusedPlanningWorkspace(targetDir, focusedIntake, ['.jumao/intake-answers.json']);
  }

  const force = options.force === true;
  const filledFiles = filledCoreFiles(targetDir);

  if (!force && filledFiles.length > 0) {
    return {
      ok: false,
      message: `Core files already have valid content: ${filledFiles.join(', ')}. Re-run with --force to overwrite.`
    };
  }

  const files = renderCoreFiles(answers);
  for (const [file, text] of Object.entries(files)) {
    const fullPath = path.join(targetDir, file);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, text, 'utf8');
  }

  return {
    ok: true,
    writtenFiles: Object.keys(files),
    strictResult: validateStrictWorkspace(targetDir)
  };
}

function writeFocusedPlanningWorkspace(targetDir, focusedIntake, writtenFiles) {
  const skippedFiles = [];
  const writeGenerated = (file, text) => {
    const fullPath = path.join(targetDir, file);
    if (fs.existsSync(fullPath)) {
      const existing = fs.readFileSync(fullPath, 'utf8').trim();
      if (existing && !existing.includes(generatedMarker)) {
        skippedFiles.push(file);
        return;
      }
    }
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, text, 'utf8');
    writtenFiles.push(file);
  };

  const agentsPath = path.join(targetDir, 'AGENTS.md');
  if (!fs.existsSync(agentsPath)) {
    fs.copyFileSync(path.join(rootDir, 'AGENTS.md'), agentsPath);
    writtenFiles.push('AGENTS.md');
  } else {
    skippedFiles.push('AGENTS.md');
  }

  if (focusedIntake.mode === 'new_project') {
    const answers = focusedIntake.answers;
    writeGenerated('product/product-brief.md', renderFocusedProductBrief(answers));
    writeGenerated('product/scope-gate.md', renderFocusedScopeGate(answers));
    writeGenerated('product/screen-states.md', renderFocusedScreenStates(answers));
    writeGenerated('product/data-safety.md', renderFocusedDataSafety());
    writeGenerated('tasks/codex-task-pack.md', renderFocusedCodexTaskPack(answers));
  } else {
    const answers = focusedIntake.answers;
    const workspaceContext = existingWorkspaceContext(targetDir);
    writeGenerated('changes/current-change.md', renderExistingChangeBrief(answers, workspaceContext));
    writeGenerated('tasks/codex-change-task-pack.md', renderExistingChangeTaskPack(answers, workspaceContext));
  }

  return {
    ok: true,
    intakeOnly: true,
    mode: focusedIntake.mode,
    writtenFiles,
    skippedFiles
  };
}

function renderFocusedProductBrief(answers) {
  return [
    '# Product Brief',
    '',
    generatedMarker,
    '',
    '## 你想做什么',
    valueOrPending(answers.idea),
    '',
    '## 你希望它能做哪些事',
    valueOrPending(answers.features),
    '',
    '## 你想先在哪儿用它',
    platformUsageDescription(answers.platform),
    '',
    '## 先不要自动加',
    '- 登录、支付、订阅、后台或云服务，除非项目主人后续明确提出。'
  ].join('\n') + '\n';
}

function renderFocusedScopeGate(answers) {
  return [
    '# First-Version Scope',
    '',
    generatedMarker,
    '',
    '## 这次先做',
    valueOrPending(answers.features),
    '',
    '## 先别自己加',
    '- 没有被说到的登录、支付、订阅、后台、云同步或第三方服务。'
  ].join('\n') + '\n';
}

function renderFocusedScreenStates(answers) {
  return [
    '# Screen States',
    '',
    generatedMarker,
    '',
    '| Screen | User goal | Loading | Empty | Error | Permission denied | Success |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    `| 最小首页骨架 | ${markdownCell(valueOrPending(answers.features))} | 待确认 | 待确认 | 待确认 | 待确认 | 待确认 |`,
    '',
    '## 待确认',
    '- 首页具体内容、页面数量和异常状态，必须在实现前与项目主人确认。'
  ].join('\n') + '\n';
}

function renderFocusedDataSafety() {
  return [
    '# Data Safety',
    '',
    generatedMarker,
    '',
    '## 当前已知',
    '- 本轮问答没有确认需要收集、保存或共享的用户数据。',
    '',
    '## 待确认',
    '- 如需任何用户数据、第三方服务、账号、云同步或分析工具，必须先补充用途、保存位置、删除方式和第三方边界。',
    '- 在确认前，不要实现数据收集、上传或第三方 SDK。'
  ].join('\n') + '\n';
}

function renderFocusedCodexTaskPack(answers) {
  return [
    '# Jumao Codex Task Pack',
    '',
    generatedMarker,
    '',
    '## 你想做什么',
    valueOrPending(answers.idea),
    '',
    '## 你希望它能做哪些事',
    valueOrPending(answers.features),
    '',
    '## 你想先在哪儿用它',
    platformUsageDescription(answers.platform),
    '',
    '## 受影响的页面和代码区域',
    ...newProjectAffectedAreas(answers.platform).map((item) => `- ${item}`),
    '',
    '## 自动识别出的保护项',
    '- 不覆盖当前目录中已有的用户文件和资料。',
    '- 不添加用户没有提出的登录、支付、订阅、后台、云服务或第三方 SDK。',
    '',
    '## Jumao 整理出的第一阶段开发步骤',
    ...firstStageTasks(answers.platform).map((item) => `- ${item}`),
    '',
    '## 开发前确实需要确认的事',
    ...questionsNeedingConfirmation(answers).map((item) => `- ${item}`),
    '',
    '## 测试与发布检查',
    ...newProjectVerificationItems(answers.platform).map((item) => `- ${item}`),
    '',
    '## 开始前',
    '请先读取 AGENTS.md、product/product-brief.md、product/scope-gate.md、product/screen-states.md、product/data-safety.md 和本文件。',
    '先总结想做什么、希望它能做哪些事、需要确认的事和第一阶段任务；在项目主人确认前，不要修改代码。'
  ].join('\n') + '\n';
}

function newProjectAffectedAreas(platform) {
  if (platform === 'iPhone') return ['先检查 iPhone 工程和最小首页入口；不存在时再创建最小工程。'];
  if (platform === 'Mac') return ['先检查 macOS 工程和最小窗口入口；不存在时再创建最小工程。'];
  if (platform === '网页') return ['先检查网页工程和最小首页入口；不预先指定框架。'];
  return ['使用方式暂未确定，先不要创建特定类型的源码工程。'];
}

function newProjectVerificationItems(platform) {
  if (platform === 'iPhone') return ['确认 iPhone 工程能够构建并运行。', '验证第一版的一次完整操作和最小错误状态。', '发布前再确认签名、隐私说明和分发方式。'];
  if (platform === 'Mac') return ['确认 macOS 工程能够构建并运行。', '验证第一版的一次完整操作和最小错误状态。', '发布前再确认签名、公证和分发方式。'];
  if (platform === '网页') return ['确认网页能够在本地启动。', '验证第一版的一次完整操作和最小错误状态。', '发布前再确认部署地址、隐私说明和回滚方式。'];
  return ['使用方式确定后再选择对应的构建、测试和发布检查。'];
}

function renderExistingChangeBrief(answers, context) {
  return [
    '# Current Change Brief',
    '',
    generatedMarker,
    '',
    '## Jumao 对需求的理解',
    valueOrPending(answers.requestedChange),
    '',
    '## 受影响的页面和代码区域',
    ...context.affectedAreas.map((item) => `- ${item}`),
    '',
    '## 自动识别出的保护项',
    ...context.protectionItems.map((item) => `- ${item}`),
    '',
    '## 确实需要确认的未知项',
    ...context.unknowns.map((item) => `- ${item}`),
    '',
    '## 说明',
    '- 这是本次改动的独立资料，不覆盖已有产品文档。',
    '- 以上内容来自当前项目的只读扫描；没有证据的业务规则不会被自动编造。'
  ].join('\n') + '\n';
}

function renderExistingChangeTaskPack(answers, context) {
  return [
    '# Jumao Codex Change Task Pack',
    '',
    generatedMarker,
    '',
    '## Jumao 对需求的理解',
    valueOrPending(answers.requestedChange),
    '',
    '## 受影响的页面和代码区域',
    ...context.affectedAreas.map((item) => `- ${item}`),
    '',
    '## 自动识别出的保护项',
    ...context.protectionItems.map((item) => `- ${item}`),
    '',
    '## 确实需要确认的未知项',
    ...context.unknowns.map((item) => `- ${item}`),
    '',
    '## 第一阶段最小任务',
    '- 先阅读 AGENTS.md、现有产品资料、测试和 changes/current-change.md。',
    '- 根据用户描述定位直接相关的页面和代码，不扩大到无关模块。',
    '- 先总结要改哪里、可能影响什么和最小验证方式；确认前不要修改代码。',
    '',
    '## 测试与发布检查',
    ...context.verificationItems.map((item) => `- ${item}`),
    '',
    '## 禁止擅自假设',
    '- 不要扩大到未说明的功能，不要覆盖已有用户文档。'
  ].join('\n') + '\n';
}

function existingWorkspaceContext(targetDir) {
  const inspection = inspectWorkspace(targetDir);
  if (!inspection.ok) {
    return {
      affectedAreas: ['需要先读取当前项目，再定位与用户描述直接相关的页面和代码。'],
      protectionItems: ['不要修改与本次描述无关的现有功能。'],
      unknowns: ['当前项目无法完成只读扫描，需要先确认目录访问是否正常。'],
      verificationItems: ['修复后运行项目已有测试和构建检查。']
    };
  }

  const project = inspection.result.project;
  const facts = [
    project.platforms.length > 0 ? `项目类型：${project.platforms.join('、')}` : '',
    project.languages.length > 0 ? `语言：${project.languages.join('、')}` : '',
    project.buildSystems.length > 0 ? `构建方式：${project.buildSystems.join('、')}` : ''
  ].filter(Boolean);
  const affectedAreas = [
    facts.length > 0
      ? `当前只读扫描识别到${facts.join('；')}。`
      : '当前扫描没有足够证据指向具体技术区域。',
    '具体文件必须在读取源码和现有资料后按用户描述定位，不能凭问答猜测。'
  ];
  const protectionItems = [
    '保持与本次描述无关的现有功能不变。',
    ...(project.hasTests ? ['保留并运行当前项目已有测试。'] : []),
    ...(project.buildSystems.length > 0 ? [`保持现有 ${project.buildSystems.join('、')} 构建方式可用。`] : []),
    '不覆盖已有产品资料和用户维护的文档。'
  ];
  const unknowns = [
    '与这次改动直接相关的页面、代码入口和业务规则，需要先读取当前项目后确认。'
  ];
  const verificationItems = [
    project.hasTests ? '运行现有测试，并为这次改动补充最小回归验证。' : '先确认项目当前使用的测试方式，再补充最小回归验证。',
    project.buildSystems.length > 0
      ? `运行现有 ${project.buildSystems.join('、')} 构建检查。`
      : '确认项目的构建方式并完成一次本地构建。',
    '发布前确认没有修改无关功能、用户数据或权限边界。'
  ];
  return { affectedAreas, protectionItems, unknowns, verificationItems };
}

function firstStageTasks(platform) {
  if (platform === 'iPhone') {
    return [
      '确认是否已有 iPhone App 的 Xcode 工程。',
      '如果没有，先创建一个只面向 iPhone 的最小可运行工程。',
      '只实现一个最小首页骨架，再向项目主人确认下一步。',
      '不先接登录、支付、订阅、后台或云服务。'
    ];
  }
  if (platform === 'Mac') {
    return [
      '确认是否已有 macOS App 的 Xcode 工程。',
      '如果没有，先创建一个只面向 macOS 的最小可运行工程。',
      '只实现一个最小 Mac 窗口或入口骨架，再向项目主人确认下一步。',
      '不先接登录、支付、订阅、后台或云服务。'
    ];
  }
  if (platform === '网页') {
    return [
      '确认当前目录是否已有网页工程。',
      '如果没有，先与项目主人确认最简单的网页工程形式。',
      '只实现一个最小首页或入口骨架，再向项目主人确认下一步。',
      '不先接登录、支付、订阅、后台或云服务。'
    ];
  }
  return [
    '先确认你想先在哪儿用它。',
    '确定后再创建一个最小可运行工程。',
    '只实现一个最小首页或入口骨架，再向项目主人确认下一步。',
    '不先接登录、支付、订阅、后台或云服务。'
  ];
}

function questionsNeedingConfirmation(answers) {
  const questions = [];
  if (!hasValue(answers.features)) {
    questions.push('还没有说清楚希望它能做哪些事。');
  }
  if (!hasValue(answers.platform)) {
    questions.push('使用方式还没有选择。');
  } else if (answers.platform === '还没想好') {
    questions.push('使用方式暂未确定，创建源码工程前需要再确认。');
  }
  return questions.length > 0 ? questions : ['暂时没有会阻止第一步开发的其他问题。'];
}

function valueOrPending(value) {
  return hasValue(value) ? value.trim() : '待确认';
}

function platformUsageDescription(value) {
  if (value === 'iPhone') return '先在 iPhone 上使用';
  if (value === 'Mac') return '先在 Mac 上使用';
  if (value === '网页') return '先通过网页使用';
  return '使用方式暂未确定';
}

function markdownCell(value) {
  return value.replaceAll('|', '\\|').replaceAll('\n', '<br>');
}

function focusedIntakeFrom(answers) {
  if (answers?.newProject && typeof answers.newProject === 'object') {
    return { mode: 'new_project', answers: normalizeNewProjectAnswers(answers.newProject) };
  }
  if (answers?.existingProject && typeof answers.existingProject === 'object') {
    return { mode: 'existing_project', answers: answers.existingProject };
  }
  return null;
}

function normalizeNewProjectAnswers(answers) {
  const idea = stringValue(answers.idea) || stringValue(answers.projectSummary);
  const features = stringValue(answers.features)
    || listOrTextValue(answers.coreFeatures)
    || stringValue(answers.firstVersion)
    || stringValue(answers.primaryGoal);
  const restoredPlatform = stringValue(answers.platform) || stringValue(answers.targetPlatform);
  const platform = ['iPhone', 'Mac', '网页', '还没想好'].includes(restoredPlatform)
    ? restoredPlatform
    : '';
  return { idea, features, firstVersion: features, platform };
}

function stringValue(value) {
  return typeof value === 'string' ? value.trim() : '';
}

function listOrTextValue(value) {
  if (Array.isArray(value)) return value.filter((item) => hasValue(item)).join('、');
  return stringValue(value);
}

function filledCoreFiles(targetDir) {
  return coreFiles.filter((file) => {
    const fullPath = path.join(targetDir, file);
    if (!fs.existsSync(fullPath)) return false;
    const text = fs.readFileSync(fullPath, 'utf8');
    return validateCoreFile(file, text).length === 0;
  });
}

function renderCoreFiles(answers) {
  return {
    'product/product-brief.zh-CN.md': renderProductBrief(answers),
    'product/scope-gate.zh-CN.md': renderScopeGate(answers),
    'product/screen-states.zh-CN.md': renderScreenStates(answers),
    'product/data-safety.zh-CN.md': renderDataSafety(answers)
  };
}

function renderProductBrief(answers) {
  const lines = [
    '# 产品简报',
    '',
    `主要用户：${answers.primaryUser}`,
    `第一版先证明一件事：${answers.firstVersionGoal}`,
    `用户能完成：${answers.userCanDo}`
  ];

  if (hasValue(answers.successEvidence)) lines.push(`我们能看到的证据：${answers.successEvidence}`);
  if (hasValue(answers.cannotCollect)) lines.push(`不能收集：${answers.cannotCollect}`);
  if (hasItems(answers.humanConfirmActions)) {
    lines.push(`会影响真实用户或钱的动作：${listSentence(answers.humanConfirmActions)}`);
  }
  return lines.join('\n') + '\n';
}

function renderScopeGate(answers) {
  const lines = [
    '# 范围门禁',
    '',
    '## 首版必须做',
    bulletList(answers.mustDo),
    '',
    '## 首版明确不做',
    bulletList(answers.wontDo)
  ];

  if (hasItems(answers.aiMustNotAdd)) {
    lines.push('', '## 不要让 AI 自己加', bulletList(answers.aiMustNotAdd));
  }
  if (hasItems(answers.humanConfirmActions)) {
    lines.push('', '## 需要人工确认的动作', bulletList(answers.humanConfirmActions));
  }
  return lines.join('\n') + '\n';
}

function renderScreenStates(answers) {
  const screen = answers.mainScreen ?? {};
  const fields = [
    ['页面', screen.name],
    ['用户想做什么', screen.userGoal],
    ['加载中', screen.loading],
    ['空状态', screen.empty],
    ['错误状态', screen.error],
    ['成功状态', screen.success],
    ['权限拒绝', screen.permissionDenied]
  ].filter(([, value]) => hasValue(value));
  return [
    '# 页面状态',
    '',
    `| ${fields.map(([title]) => title).join(' | ')} |`,
    `|${fields.map(() => '---').join('|')}|`,
    `| ${fields.map(([, value]) => value).join(' | ')} |`
  ].join('\n') + '\n';
}

function renderDataSafety(answers) {
  const data = answers.dataSafety ?? {};
  const lines = [
    '# 数据安全',
    ''
  ];
  for (const value of [data.collects, data.thirdParties, data.doesNotCollect, data.deletion, data.retention]) {
    if (hasValue(value)) lines.push(`${value}。`);
  }
  return lines.join('\n') + '\n';
}

function splitList(value) {
  return value
    .split(/[，,、]/)
    .map((item) => item.trim())
    .filter(Boolean);
}

function setAnswerAtPath(answers, answerPath, value) {
  const parts = answerPath.split('.');
  const key = parts.pop();
  const target = parts.reduce((current, part) => current[part] ||= {}, answers);
  target[key] = value;
}

function bulletList(items) {
  return (items ?? []).map((item) => `- ${item}`).join('\n');
}

function listSentence(items) {
  return (items ?? []).join('、');
}

function hasValue(value) {
  return typeof value === 'string' && value.trim().length > 0;
}

function hasItems(items) {
  return Array.isArray(items) && items.length > 0;
}
