import fs from 'node:fs';
import path from 'node:path';
import { auditWorkspace } from './core/audit.js';
import { missingRequiredFiles, requiredProductFiles, validateStrictWorkspace } from './core/strict-check.js';

const rootDir = path.resolve(new URL('..', import.meta.url).pathname);

const bilingualTemplates = [
  ['templates/product-brief.zh-CN.md', 'product/product-brief.zh-CN.md'],
  ['templates/product-brief.md', 'product/product-brief.md'],
  ['templates/scope-gate.zh-CN.md', 'product/scope-gate.zh-CN.md'],
  ['templates/scope-gate.md', 'product/scope-gate.md'],
  ['templates/screen-states.zh-CN.md', 'product/screen-states.zh-CN.md'],
  ['templates/screen-states.md', 'product/screen-states.md'],
  ['templates/data-safety.zh-CN.md', 'product/data-safety.zh-CN.md'],
  ['templates/data-safety.md', 'product/data-safety.md'],
  ['templates/release-proof.zh-CN.md', 'proof/release-proof.zh-CN.md'],
  ['templates/release-proof.md', 'proof/release-proof.md']
];

export async function main(argv = process.argv.slice(2), io = process) {
  const [command, ...args] = argv;

  if (!command || command === '--help' || command === '-h') {
    io.stdout.write(helpText());
    return 0;
  }

  if (command === 'init') return initCommand(args, io);
  if (command === 'new') return newCommand(args, io);
  if (command === 'check') return checkCommand(args, io);
  if (command === 'audit') return auditCommand(args, io);
  if (command === 'pack') return packCommand(args, io);

  io.stderr.write(`Unknown command: ${command}\n\n${helpText()}`);
  return 1;
}

function helpText() {
  return [
    '橘猫 / Jumao',
    '',
    'Usage:',
    '  jumao init [dir]',
    '  jumao new <product-name> --dir [dir]',
    '  jumao check [dir] [--strict]',
    '  jumao audit [dir] [--write]',
    '  jumao pack [dir]',
    '',
    'Jumao does not call AI APIs. It creates local files for the AI coding tool you use.'
  ].join('\n') + '\n';
}

function initCommand(args, io) {
  const targetDir = path.resolve(args[0] || '.');
  ensureDir(targetDir);
  copyFile('README.zh-CN.md', path.join(targetDir, 'README.zh-CN.md'));
  copyFile('README.md', path.join(targetDir, 'README.md'));
  copyFile('AGENTS.md', path.join(targetDir, 'AGENTS.md'));
  copyFile('CLAUDE.md', path.join(targetDir, 'CLAUDE.md'));
  copyTree('docs', path.join(targetDir, 'docs'));
  copyTree('templates', path.join(targetDir, 'templates'));
  copyTree('checklists', path.join(targetDir, 'checklists'));
  ensureDir(path.join(targetDir, 'product'));
  ensureDir(path.join(targetDir, 'proof'));
  for (const [source, target] of bilingualTemplates) {
    copyFile(source, path.join(targetDir, target));
  }
  io.stdout.write(`Initialized Jumao files in ${targetDir}\n`);
  return 0;
}

function newCommand(args, io) {
  const productName = args.find((arg) => !arg.startsWith('--'));
  if (!productName) {
    io.stderr.write('Missing product name.\n');
    return 1;
  }

  const targetDir = path.resolve(readOption(args, '--dir') || slugify(productName));
  ensureDir(targetDir);
  ensureDir(path.join(targetDir, 'product'));
  ensureDir(path.join(targetDir, 'proof'));

  copyFile('AGENTS.md', path.join(targetDir, 'AGENTS.md'));
  copyFile('CLAUDE.md', path.join(targetDir, 'CLAUDE.md'));

  for (const [source, target] of bilingualTemplates) {
    const output = path.join(targetDir, target);
    copyFile(source, output);
    replaceInFile(output, {
      '产品简报': `产品简报：${productName}`,
      'Product Brief': `Product Brief: ${productName}`
    });
  }

  const zhReadme = [
    `# ${productName}`,
    '',
    '这个目录由橘猫生成。先填写 product/ 下的文件，再把任务交给 AI 编程工具。'
  ].join('\n') + '\n';
  const enReadme = [
    `# ${productName}`,
    '',
    'This workspace was generated by Jumao. Fill the product files first,',
    'then hand the task to your AI coding tool.'
  ].join('\n') + '\n';

  fs.writeFileSync(path.join(targetDir, 'README.zh-CN.md'), zhReadme, 'utf8');
  fs.writeFileSync(path.join(targetDir, 'README.md'), enReadme, 'utf8');

  io.stdout.write(`Created product workspace in ${targetDir}\n`);
  return 0;
}

function checkCommand(args, io) {
  const { targetDir, strict } = parseCheckArgs(args);
  const missing = missingRequiredFiles(targetDir);

  if (missing.length === 0 && !strict) {
    io.stdout.write(`Jumao check passed for ${targetDir}\n`);
    return 0;
  }

  if (!strict) {
    io.stdout.write(`Jumao check found missing files in ${targetDir}:\n`);
    for (const file of missing) io.stdout.write(`- ${file}\n`);
    return 1;
  }

  const result = validateStrictWorkspace(targetDir);
  if (result.errors.length === 0) {
    io.stdout.write(`Jumao strict check passed for ${targetDir}\n`);
    writeWarnings(result.warnings, io);
    return 0;
  }

  io.stdout.write(`Jumao strict check found gaps in ${targetDir}:\n\n`);
  io.stdout.write('Errors:\n');
  for (const error of result.errors) io.stdout.write(`- ${error}\n`);
  writeWarnings(result.warnings, io);
  return 1;
}

function auditCommand(args, io) {
  const { targetDir, write } = parseAuditArgs(args);
  const result = auditWorkspace(targetDir);

  if (!result.ok) {
    io.stderr.write(`${result.message}\n`);
    return 1;
  }

  if (write) {
    const tasksDir = path.join(targetDir, 'tasks');
    ensureDir(tasksDir);
    fs.writeFileSync(path.join(tasksDir, 'audit-report.md'), result.report, 'utf8');
  }

  io.stdout.write(result.report);
  return 0;
}

function packCommand(args, io) {
  const targetDir = path.resolve(args[0] || '.');
  const sections = [];
  for (const file of requiredProductFiles.filter((item) => item.endsWith('.md'))) {
    const fullPath = path.join(targetDir, file);
    if (fs.existsSync(fullPath)) {
      sections.push(`\n\n## ${file}\n\n${fs.readFileSync(fullPath, 'utf8').trim()}`);
    }
  }

  if (sections.length === 0) {
    io.stderr.write('No product files found. Run jumao new first.\n');
    return 1;
  }

  const outputPath = path.join(targetDir, 'jumao-task-pack.md');
  const taskPack = [
    '# 橘猫 AI 任务包',
    '',
    '把这份文件交给你的 AI 编程工具。先让它总结目标、缺口和下一步安全动作。',
    sections.join('')
  ].join('\n') + '\n';

  fs.writeFileSync(outputPath, taskPack, 'utf8');
  io.stdout.write(`Wrote ${outputPath}\n`);
  return 0;
}

function copyFile(relativeSource, target) {
  ensureDir(path.dirname(target));
  fs.copyFileSync(path.join(rootDir, relativeSource), target);
}

function copyTree(relativeSource, target) {
  const source = path.join(rootDir, relativeSource);
  ensureDir(target);
  for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
    const sourcePath = path.join(source, entry.name);
    const targetPath = path.join(target, entry.name);
    if (entry.isDirectory()) copyTree(path.relative(rootDir, sourcePath), targetPath);
    else fs.copyFileSync(sourcePath, targetPath);
  }
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function readOption(args, name) {
  const index = args.indexOf(name);
  if (index === -1) return undefined;
  return args[index + 1];
}

function parseCheckArgs(args) {
  const strictFlags = new Set(['--strict', '-s']);
  const strict = args.some((arg) => strictFlags.has(arg));
  const positional = args.filter((arg) => !strictFlags.has(arg));
  return {
    targetDir: path.resolve(positional[0] || '.'),
    strict
  };
}

function parseAuditArgs(args) {
  const write = args.includes('--write');
  const positional = args.filter((arg) => arg !== '--write');
  return {
    targetDir: path.resolve(positional[0] || '.'),
    write
  };
}

function writeWarnings(warnings, io) {
  if (warnings.length === 0) return;

  io.stdout.write('\nWarnings:\n');
  for (const warning of warnings) io.stdout.write(`- ${warning}\n`);
}

function replaceInFile(file, replacements) {
  let text = fs.readFileSync(file, 'utf8');
  for (const [from, to] of Object.entries(replacements)) {
    text = text.replace(from, to);
  }
  fs.writeFileSync(file, text, 'utf8');
}

function slugify(input) {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fa5]+/gi, '-')
    .replace(/^-+|-+$/g, '') || 'my-product';
}
