import fs from 'node:fs';
import path from 'node:path';

const rootDir = path.resolve(new URL('..', import.meta.url).pathname);

const bilingualTemplates = [
  ['templates/product-brief.zh-CN.md', 'product/product-brief.zh-CN.md'],
  ['templates/product-brief.md', 'product/product-brief.md'],
  ['templates/scope-gate.zh-CN.md', 'product/scope-gate.zh-CN.md'],
  ['templates/scope-gate.md', 'product/scope-gate.md'],
  ['templates/screen-states.zh-CN.md', 'product/screen-states.zh-CN.md'],
  ['templates/screen-states.md', 'product/screen-states.md'],
  ['templates/data-safety.zh-CN.md', 'product/data-safety.zh-CN.md'],
  ['templates/data-safety.md', 'product/data-safety.md'],
  ['templates/release-proof.zh-CN.md', 'proof/release-proof.zh-CN.md'],
  ['templates/release-proof.md', 'proof/release-proof.md']
];

const requiredProductFiles = [
  'product/product-brief.zh-CN.md',
  'product/scope-gate.zh-CN.md',
  'product/screen-states.zh-CN.md',
  'product/data-safety.zh-CN.md',
  'proof/release-proof.zh-CN.md',
  'AGENTS.md',
  'CLAUDE.md'
];

const strictContentFiles = requiredProductFiles.filter(
  (file) => file.startsWith('product/') || file.startsWith('proof/')
);

const coreContentFiles = strictContentFiles.filter((file) => file.startsWith('product/'));
const completionProofFile = 'proof/release-proof.zh-CN.md';

const placeholderTerms = [
  'TODO',
  'TBD',
  'placeholder',
  'fill in',
  'to be filled',
  '待填写',
  '请填写',
  '未填写',
  '待补充',
  '稍后补充',
  '以后再说',
  '后面再说',
  '先空着',
  '暂无',
  '无内容',
  '写一下',
  '随便写',
  '已填写',
  '测试',
  '示例',
  '占位',
  '???',
  'xxx',
  '...',
  '——'
];

const lowQualityLines = new Set([
  '已填写',
  '已填写。',
  '做一个app',
  '做一个app。',
  '做一个网站',
  '做一个网站。',
  '做一个小工具',
  '做一个小工具。',
  '用户都可以用',
  '用户都可以用。',
  '越多人越好',
  '越多人越好。',
  '先上线再说',
  '先上线再说。',
  '后面再补',
  '后面再补。',
  '无',
  '无。',
  '没有',
  '没有。',
  '测试',
  '测试。'
]);

const productBriefRequiredLabels = [
  '主要用户',
  '第一版先证明一件事',
  '用户能完成',
  '我们能看到的证据',
  '不能承诺',
  '不能收集',
  '会影响真实用户或钱的动作'
];

const scopeRequiredSections = [
  '首版必须做',
  '首版明确不做',
  '不要让 AI 自己加',
  '需要人工确认的动作'
];

const screenRequiredColumns = ['页面', '用户想做什么', '加载中', '空状态', '错误状态', '成功状态', '权限拒绝'];

export async function main(argv = process.argv.slice(2), io = process) {
  const [command, ...args] = argv;

  if (!command || command === '--help' || command === '-h') {
    io.stdout.write(helpText());
    return 0;
  }

  if (command === 'init') return initCommand(args, io);
  if (command === 'new') return newCommand(args, io);
  if (command === 'check') return checkCommand(args, io);
  if (command === 'pack') return packCommand(args, io);

  io.stderr.write(`Unknown command: ${command}\n\n${helpText()}`);
  return 1;
}

function helpText() {
  return [
    '橘猫 / Jumao',
    '',
    'Usage:',
    '  jumao init [dir]',
    '  jumao new <product-name> --dir [dir]',
    '  jumao check [dir] [--strict]',
    '  jumao pack [dir]',
    '',
    'Jumao does not call AI APIs. It creates local files for the AI coding tool you use.'
  ].join('\n') + '\n';
}

function initCommand(args, io) {
  const targetDir = path.resolve(args[0] || '.');
  ensureDir(targetDir);
  copyFile('README.zh-CN.md', path.join(targetDir, 'README.zh-CN.md'));
  copyFile('README.md', path.join(targetDir, 'README.md'));
  copyFile('AGENTS.md', path.join(targetDir, 'AGENTS.md'));
  copyFile('CLAUDE.md', path.join(targetDir, 'CLAUDE.md'));
  copyTree('docs', path.join(targetDir, 'docs'));
  copyTree('templates', path.join(targetDir, 'templates'));
  copyTree('checklists', path.join(targetDir, 'checklists'));
  ensureDir(path.join(targetDir, 'product'));
  ensureDir(path.join(targetDir, 'proof'));
  for (const [source, target] of bilingualTemplates) {
    copyFile(source, path.join(targetDir, target));
  }
  io.stdout.write(`Initialized Jumao files in ${targetDir}\n`);
  return 0;
}

function newCommand(args, io) {
  const productName = args.find((arg) => !arg.startsWith('--'));
  if (!productName) {
    io.stderr.write('Missing product name.\n');
    return 1;
  }

  const targetDir = path.resolve(readOption(args, '--dir') || slugify(productName));
  ensureDir(targetDir);
  ensureDir(path.join(targetDir, 'product'));
  ensureDir(path.join(targetDir, 'proof'));

  copyFile('AGENTS.md', path.join(targetDir, 'AGENTS.md'));
  copyFile('CLAUDE.md', path.join(targetDir, 'CLAUDE.md'));

  for (const [source, target] of bilingualTemplates) {
    const output = path.join(targetDir, target);
    copyFile(source, output);
    replaceInFile(output, {
      '产品简报': `产品简报：${productName}`,
      'Product Brief': `Product Brief: ${productName}`
    });
  }

  const zhReadme = [
    `# ${productName}`,
    '',
    '这个目录由橘猫生成。先填写 product/ 下的文件，再把任务交给 AI 编程工具。'
  ].join('\n') + '\n';
  const enReadme = [
    `# ${productName}`,
    '',
    'This workspace was generated by Jumao. Fill the product files first,',
    'then hand the task to your AI coding tool.'
  ].join('\n') + '\n';

  fs.writeFileSync(path.join(targetDir, 'README.zh-CN.md'), zhReadme, 'utf8');
  fs.writeFileSync(path.join(targetDir, 'README.md'), enReadme, 'utf8');

  io.stdout.write(`Created product workspace in ${targetDir}\n`);
  return 0;
}

function checkCommand(args, io) {
  const { targetDir, strict } = parseCheckArgs(args);
  const missing = requiredProductFiles.filter((file) => !fs.existsSync(path.join(targetDir, file)));

  if (missing.length === 0 && !strict) {
    io.stdout.write(`Jumao check passed for ${targetDir}\n`);
    return 0;
  }

  if (!strict) {
    io.stdout.write(`Jumao check found missing files in ${targetDir}:\n`);
    for (const file of missing) io.stdout.write(`- ${file}\n`);
    return 1;
  }

  const result = runStrictCheck(targetDir, missing);
  if (result.errors.length === 0) {
    io.stdout.write(`Jumao strict check passed for ${targetDir}\n`);
    writeWarnings(result.warnings, io);
    return 0;
  }

  io.stdout.write(`Jumao strict check found gaps in ${targetDir}:\n\n`);
  io.stdout.write('Errors:\n');
  for (const error of result.errors) io.stdout.write(`- ${error}\n`);
  writeWarnings(result.warnings, io);
  return 1;
}

function packCommand(args, io) {
  const targetDir = path.resolve(args[0] || '.');
  const sections = [];
  for (const file of requiredProductFiles.filter((item) => item.endsWith('.md'))) {
    const fullPath = path.join(targetDir, file);
    if (fs.existsSync(fullPath)) {
      sections.push(`\n\n## ${file}\n\n${fs.readFileSync(fullPath, 'utf8').trim()}`);
    }
  }

  if (sections.length === 0) {
    io.stderr.write('No product files found. Run jumao new first.\n');
    return 1;
  }

  const outputPath = path.join(targetDir, 'jumao-task-pack.md');
  const taskPack = [
    '# 橘猫 AI 任务包',
    '',
    '把这份文件交给你的 AI 编程工具。先让它总结目标、缺口和下一步安全动作。',
    sections.join('')
  ].join('\n') + '\n';

  fs.writeFileSync(outputPath, taskPack, 'utf8');
  io.stdout.write(`Wrote ${outputPath}\n`);
  return 0;
}

function copyFile(relativeSource, target) {
  ensureDir(path.dirname(target));
  fs.copyFileSync(path.join(rootDir, relativeSource), target);
}

function copyTree(relativeSource, target) {
  const source = path.join(rootDir, relativeSource);
  ensureDir(target);
  for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
    const sourcePath = path.join(source, entry.name);
    const targetPath = path.join(target, entry.name);
    if (entry.isDirectory()) copyTree(path.relative(rootDir, sourcePath), targetPath);
    else fs.copyFileSync(sourcePath, targetPath);
  }
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function readOption(args, name) {
  const index = args.indexOf(name);
  if (index === -1) return undefined;
  return args[index + 1];
}

function parseCheckArgs(args) {
  const strictFlags = new Set(['--strict', '-s']);
  const strict = args.some((arg) => strictFlags.has(arg));
  const positional = args.filter((arg) => !strictFlags.has(arg));
  return {
    targetDir: path.resolve(positional[0] || '.'),
    strict
  };
}

function runStrictCheck(targetDir, missing) {
  const result = {
    errors: missing.map((file) => `${file}: missing required file`),
    warnings: []
  };

  for (const file of ['AGENTS.md', 'CLAUDE.md']) {
    const fullPath = path.join(targetDir, file);
    if (fs.existsSync(fullPath) && fs.readFileSync(fullPath, 'utf8').trim().length === 0) {
      result.errors.push(`${file}: file is empty`);
    }
  }

  for (const file of coreContentFiles) {
    const fullPath = path.join(targetDir, file);
    if (!fs.existsSync(fullPath)) continue;

    const text = fs.readFileSync(fullPath, 'utf8');
    for (const error of validateCoreFile(file, text)) result.errors.push(`${file}: ${error}`);
  }

  const proofPath = path.join(targetDir, completionProofFile);
  if (fs.existsSync(proofPath)) {
    const proofText = fs.readFileSync(proofPath, 'utf8');
    if (!isCompletionProofFilled(proofText)) {
      result.warnings.push(`${completionProofFile}: completion proof is not filled yet`);
    }
  }

  return result;
}

function writeWarnings(warnings, io) {
  if (warnings.length === 0) return;

  io.stdout.write('\nWarnings:\n');
  for (const warning of warnings) io.stdout.write(`- ${warning}\n`);
}

function validateCoreFile(file, text) {
  const errors = commonContentErrors(text);

  if (file === 'product/product-brief.zh-CN.md') {
    for (const label of productBriefRequiredLabels) {
      if (!hasFilledValueAfterLabel(text, label)) {
        errors.push(`missing valid content for "${label}"`);
      }
    }
  }

  if (file === 'product/scope-gate.zh-CN.md') {
    for (const section of scopeRequiredSections) {
      if (countValidBullets(getSectionByHeading(text, section)) === 0) {
        errors.push(`section "${section}" needs at least one valid bullet`);
      }
    }
  }

  if (file === 'product/screen-states.zh-CN.md' && !hasValidScreenStateTable(text)) {
    errors.push('needs at least one valid page state row');
  }

  if (file === 'product/data-safety.zh-CN.md' && !hasValidDataSafetyContent(text)) {
    errors.push('needs clear data collection, non-collection, third-party, deletion, and retention rules');
  }

  if (!hasEnoughUsableContent(text)) {
    errors.push('not enough usable content');
  }

  return unique(errors);
}

function commonContentErrors(text) {
  const errors = [];
  const usable = usableLines(text);

  if (usable.length === 0) {
    errors.push('no meaningful content');
    return errors;
  }

  const placeholder = usable.find((line) => containsPlaceholder(line));
  if (placeholder) errors.push(`contains placeholder "${placeholder.trim()}"`);

  const lowQuality = usable.find((line) => isLowQualityLine(line));
  if (lowQuality) errors.push(`contains low-quality content "${lowQuality.trim()}"`);

  const emptyField = usable.find((line) => hasEmptyField(line));
  if (emptyField) errors.push(`has empty field "${emptyField.trim()}"`);

  if (usable.some((line) => isEmptyBullet(line))) errors.push('has empty bullet');
  if (usable.some((line) => hasEmptyTableCells(line))) errors.push('has empty table row');

  return errors;
}

function isCompletionProofFilled(text) {
  if (commonContentErrors(text).length > 0) return false;
  return hasEnoughUsableContent(text);
}

function containsPlaceholder(text) {
  const lower = text.toLowerCase();
  if (text.includes('--') && !isTableSeparator(text)) return true;
  return placeholderTerms.some((term) => lower.includes(term.toLowerCase()));
}

function isLowQualityLine(line) {
  return lowQualityLines.has(normalizeLine(line));
}

function hasEmptyField(line) {
  const trimmed = stripBulletMarker(line.trim());
  if (trimmed.startsWith('|')) return false;
  return /^[^:：]+[:：]\s*$/.test(trimmed);
}

function isEmptyBullet(line) {
  return /^[-*]\s*$/.test(line.trim());
}

function hasEmptyTableCells(line) {
  const trimmed = line.trim();
  if (!trimmed.startsWith('|') || isTableSeparator(trimmed)) return false;
  return tableCells(trimmed).filter((cell) => cell.length === 0).length >= 2;
}

function hasFilledValueAfterLabel(text, label) {
  const line = text.split(/\r?\n/).find((item) => {
    const trimmed = stripBulletMarker(item.trim());
    return trimmed.startsWith(`${label}：`) || trimmed.startsWith(`${label}:`);
  });
  if (!line) return false;

  const value = stripBulletMarker(line.trim()).replace(new RegExp(`^${escapeRegExp(label)}[:：]\\s*`), '');
  return isValidTextValue(value, { minCjk: 6, minEnglish: 3 });
}

function getSectionByHeading(text, heading) {
  const lines = text.split(/\r?\n/);
  const start = lines.findIndex((line) => line.trim() === `## ${heading}`);
  if (start === -1) return [];

  const section = [];
  for (const line of lines.slice(start + 1)) {
    if (line.trim().startsWith('## ')) break;
    section.push(line);
  }
  return section;
}

function countValidBullets(lines) {
  return lines.filter((line) => {
    const trimmed = line.trim();
    if (!/^[-*]\s+/.test(trimmed)) return false;
    return isValidTextValue(stripBulletMarker(trimmed), { minCjk: 6, minEnglish: 3 });
  }).length;
}

function hasValidScreenStateTable(text) {
  const rows = text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.startsWith('|') && !isTableSeparator(line))
    .map((line) => tableCells(line));

  const headerIndex = rows.findIndex((cells) => screenRequiredColumns.every((column) => cells.includes(column)));
  if (headerIndex === -1) return false;

  const header = rows[headerIndex];
  const indexes = Object.fromEntries(screenRequiredColumns.map((column) => [column, header.indexOf(column)]));
  const dataRows = rows.slice(headerIndex + 1);

  return dataRows.some((row) => {
    if (screenRequiredColumns.some((column) => !row[indexes[column]])) return false;
    return screenRequiredColumns.every((column) => {
      const value = row[indexes[column]];
      if (column === '权限拒绝' && value === '不涉及') return true;
      if (column === '页面') return isValidTextValue(value, { minCjk: 2, minEnglish: 1 });
      return isValidTextValue(value, { minCjk: 4, minEnglish: 2 });
    });
  });
}

function hasValidDataSafetyContent(text) {
  const lines = usableLines(text);
  return [
    (line) => /首版不收集用户数据|收集.+数据|数据.+来源/.test(line),
    (line) => /不收集.+/.test(line),
    (line) => /首版不使用第三方服务|第三方服务.+|不给第三方/.test(line),
    (line) => /删除.+/.test(line),
    (line) => /删除后无保留数据|保留.+/.test(line)
  ].every((matcher) => lines.some((line) => matcher(line) && !containsPlaceholder(line)));
}

function hasEnoughUsableContent(text) {
  const content = usableLines(text).join('\n');
  const cjkCount = (content.match(/[\u4e00-\u9fff]/g) || []).length;
  const englishWordCount = (content.match(/[A-Za-z]+/g) || []).length;
  return cjkCount >= 30 || englishWordCount >= 15;
}

function usableLines(text) {
  return text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .filter((line) => !line.startsWith('#'))
    .filter((line) => !isTableSeparator(line));
}

function isValidTextValue(value, options = {}) {
  const text = value.trim();
  if (!text) return false;
  if (containsPlaceholder(text)) return false;
  if (isLowQualityLine(text)) return false;
  const minCjk = options.minCjk || 1;
  const minEnglish = options.minEnglish || 1;
  const cjkCount = (text.match(/[\u4e00-\u9fff]/g) || []).length;
  const englishWordCount = (text.match(/[A-Za-z]+/g) || []).length;
  return cjkCount >= minCjk || englishWordCount >= minEnglish;
}

function stripBulletMarker(line) {
  return line.replace(/^[-*]\s*/, '');
}

function tableCells(line) {
  return line
    .split('|')
    .slice(1, -1)
    .map((cell) => cell.trim());
}

function isTableSeparator(line) {
  const trimmed = line.trim();
  if (!trimmed.startsWith('|')) return false;
  return tableCells(trimmed).every((cell) => /^:?-{3,}:?$/.test(cell));
}

function normalizeLine(line) {
  return stripBulletMarker(line.trim())
    .toLowerCase()
    .replace(/\s+/g, '')
    .replace(/[，,；;：:！!？?]/g, '')
    .replace(/[。.]$/g, '。');
}

function unique(items) {
  return [...new Set(items)];
}

function escapeRegExp(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function replaceInFile(file, replacements) {
  let text = fs.readFileSync(file, 'utf8');
  for (const [from, to] of Object.entries(replacements)) {
    text = text.replace(from, to);
  }
  fs.writeFileSync(file, text, 'utf8');
}

function slugify(input) {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fa5]+/gi, '-')
    .replace(/^-+|-+$/g, '') || 'my-product';
}
